<?php

namespace ContainerH31L3x5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserInfoTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserInfoType' shared autowired service.
     *
     * @return \App\Form\UserInfoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserInfoType.php';

        return $container->privates['App\\Form\\UserInfoType'] = new \App\Form\UserInfoType();
    }
}
