<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH31L3x5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH31L3x5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH31L3x5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH31L3x5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH31L3x5\App_KernelDevDebugContainer([
    'container.build_hash' => 'H31L3x5',
    'container.build_id' => '6753e0ee',
    'container.build_time' => 1634734869,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH31L3x5');
